[package]
name = "cfn-docs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
color-eyre = "0.6.5"
cfn-lsp-schema = { path = "../cfn-lsp-schema", features = ["bundle"] }
termimad = "0.33.0"
